### ISSUE TITLE
[python]

### ISSUE THREAD

**Issue by DirtyJerz** [gongzhang/proc-bridge#13]
```
Traceback (most recent call last):
  File "c:\Users\name\Documents\python\procbridgetest\main.py", line 32, in <module>
    from procbridge import ProcBridgeServer
ImportError: cannot import name 'ProcBridgeServer'
```
Python 3.6.4
procbridge 1.0.3

solution was to add below to procbridge/`__init__`.py:

```
from procbridge.procbridge import ProcBridgeServer, ProcBridge
```

**Comment by ynx0** [comment]
@DirtyJerz, in case you haven't already updated, this has been fixed in the latest release of [procbridge-python](https://github.com/gongzhang/procbridge-python).
