### ISSUE TITLE
Swift Support

### ISSUE THREAD

**Issue by royalstream** [gongzhang/proc-bridge#16]
Hi,

I created a Swift backend for a temporary project that needed IPC between Swift and Kotlin. My temporary project is over, but this bridge is worth keeping. I'm using the new Network Framework which is nice but it requires macOS 10.14 or later. That requirement is configured inside Package.swift.

I don't have as much experience in Swift as I have in other languages, but the implementation is acceptably clean and it could be a good starting point for your "official" backend:

https://github.com/royalstream/procbridge-swift

If you like it, perhaps you can create an empty repository on your side and I can submit this implementation as a Pull Request. I could also transfer the repository but that's something I've never done before, so I'm not sure how that works.

Best,

SB

**Comment by gongzhang** [comment]
@royalstream 😎 I'll add it to the README.

**Comment by gongzhang** [comment]
@royalstream a simple PR :) https://github.com/royalstream/procbridge-swift/pull/1

**Comment by gongzhang** [comment]
https://github.com/gongzhang/procbridge/commit/d65c1ec434c55824506e489f2fff7914c7f38dba
